<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.tcknvkn</groupId>
  <artifactId>tcknvkn</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <name>tcknvkn</name>
  <description>TCKN and VKN validation library for Java.</description>
  <url>https://www.tcknvkn.com/kutuphaneler/java</url>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/licenses/MIT</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>tcknvkn.com</name>
      <email>info@tcknvkn.com</email>
      <organization>tcknvkn.com</organization>
      <organizationUrl>https://www.tcknvkn.com</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:https://github.com/tcknvkn/tcknvkn-java.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/tcknvkn/tcknvkn-java.git</developerConnection>
    <url>https://github.com/tcknvkn/tcknvkn-java</url>
  </scm>

  <properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <junit.version>5.10.2</junit.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
      </plugin>
    </plugins>
  </build>
</project>
